orders_url = "http://0.0.0.0:4455"
poll_interval = 5

[chains.monad_testnet]
chain_id = 10143
chain_type = "evm"
resolver_contract_address = "0xB0b64e0b69CB82AB9cE7c9473a4FCeE2Ad91Fce3"
provider = "https://rpc.ankr.com/monad_testnet"
private_key = "#ENV:ETH_PRIVATE_KEY"
assets = ["0xea2bb31ebb0aee264aba3730c8744d6bd76d37d0"]

[chains.base_sepolia]
chain_id = 84532
chain_type = "evm"
resolver_contract_address = "0xD7C1F4947a4cE0A79B146918233e306114e1A78A"
provider = "https://base-sepolia-rpc.publicnode.com"
private_key = "#ENV:ETH_PRIVATE_KEY"
assets = ["0x6756682b6144018dea5416640a0d0e8783e33f60"]