orders_url = "http://localhost:4455"
poll_interval = 5

[chains.eth]
chain_id = "1"
chain_type = "evm"
resolver_contract_address = ""
provider = ""
assets = ["ETH", "USDC", "DAI"]

[chains.bsc]
chain_id = "56"
chain_type = "evm"
resolver_contract_address = ""
provider = ""
assets = ["BNB", "BUSD", "USDT"]

[chains.polygon]
chain_id = "137"
chain_type = "evm"
resolver_contract_address = ""
provider = ""
assets = ["MATIC", "USDC", "DAI"]